name: Rust

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-zip:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Build with cargo
        run: |
          cargo build --release --target=x86_64-pc-windows-msvc
        shell: powershell

      - name: Zip binaries
        run: |
          New-Item -ItemType Directory -Force -Path dist
          New-Item -ItemType Directory -Force -Path carlback_utils
          New-Item -ItemType Directory -Force -Path carlback_utils/bin
          Move-Item -Path "target/x86_64-pc-windows-msvc/release/*.exe" -Destination "carlback_utils/bin/" -Force
          Compress-Archive -Path carlback_utils/bin/*.exe -Destination dist/duddde_archive.zip
        shell: powershell

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: carlback_utils_x64.zip
          path: dist/duddde_archive.zip
